add content
opentelekomcloud-docs/docs_on_docs pull request #18
Opened 2022-03-28 07:18 UTC by lourieder

2022-03-29 11:48 UTC, vladimirhasko requested changes

2022-03-29 11:48 UTC, vladimirhasko commented on doc/source/rst.rst
> +Integrating Admonitions
show all admonition types as examples how they really look like.

2022-03-29 11:48 UTC, vladimirhasko commented on doc/source/rst.rst
>  Understanding the RST
please add also info about how to work with intersection links within same page or intesection links from other page but in same document.
How to use anchors , etc
Also how to work with ordered and unordered list.

2022-03-29 15:27 UTC, gtema commented on doc/source/rst.rst
> +            :alt: This is your title
"alt" is so to say a hidden title (visible on hover if at all). The most proper way is to simply include title in the text form inside of the macros body (https://sphinxguide.readthedocs.io/en/latest/fig-num/fig.html)

2022-04-11 09:23 UTC, vladimirhasko commented
Recheck

2022-04-12 09:44 UTC, kucerakk commented
merged with https://github.com/opentelekomcloud-docs/docs_on_docs/pull/22

2022-04-12 09:44 UTC, closed without merging