add content to working with github
opentelekomcloud-docs/docs_on_docs pull request #19
Opened 2022-03-29 10:52 UTC by lourieder

2022-03-29 15:38 UTC, gtema requested changes
Maybe reuse more text as inspiration for sentence phrasing from github docs?

There are actually plenty of articles in internet which describes this topics in details:
https://www.gitkraken.com/learn/git/best-practices/git-commit-message
https://medium.com/swlh/writing-better-commit-messages-9b0b6ff60c67
https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/
https://www.toolsqa.com/git/git-fork/
...

We do not need to write the whole article about git, but it should content more text

2022-03-29 15:38 UTC, gtema commented on doc/source/git_account.rst
> +    - write short datailed commit meggsages
many typos in the word "message"

2022-04-07 08:09 UTC, kucerakk commented
content merged with https://github.com/opentelekomcloud-docs/docs_on_docs/pull/20

2022-04-07 08:09 UTC, kucerakk commented
content merged with https://github.com/opentelekomcloud-docs/docs_on_docs/pull/20

2022-04-07 08:09 UTC, closed without merging